/* Naqsh Nasir — minimal gallery + lightbox.
   Reads images/manifest.json (generated by the Drive-sync GitHub Action)
   and renders a masonry grid. No external libraries. */

(function () {
  var yearEl = document.getElementById('year');
  if (yearEl) yearEl.textContent = new Date().getFullYear();

  var gallery = document.getElementById('gallery');
  var loadingEl = document.getElementById('gallery-loading');
  var emptyEl = document.getElementById('gallery-empty');
  if (!gallery) return;

  var images = [];

  fetch('images/manifest.json', { cache: 'no-cache' })
    .then(function (res) {
      if (!res.ok) throw new Error('no manifest');
      return res.json();
    })
    .then(function (data) {
      images = (data && data.images) || [];
      render();
    })
    .catch(function () {
      render(); // treat as empty
    });

  function render() {
    if (loadingEl) loadingEl.hidden = true;
    if (!images.length) {
      if (emptyEl) emptyEl.hidden = false;
      return;
    }
    var frag = document.createDocumentFragment();
    images.forEach(function (img, i) {
      var fig = document.createElement('figure');
      fig.className = 'gallery-item';
      fig.setAttribute('role', 'button');
      fig.setAttribute('tabindex', '0');
      fig.setAttribute('aria-label', 'Open ' + (img.name || 'image'));

      var el = document.createElement('img');
      el.src = img.thumb || img.file;
      el.alt = img.name || '';
      el.loading = 'lazy';
      el.decoding = 'async';
      if (img.w && img.h) { el.width = img.w; el.height = img.h; }
      el.addEventListener('load', function () { el.classList.add('loaded'); });
      // if already cached
      if (el.complete) el.classList.add('loaded');

      fig.appendChild(el);
      fig.addEventListener('click', function () { openLightbox(i); });
      fig.addEventListener('keydown', function (e) {
        if (e.key === 'Enter' || e.key === ' ') { e.preventDefault(); openLightbox(i); }
      });
      frag.appendChild(fig);
    });
    gallery.appendChild(frag);
  }

  /* ---------- Lightbox ---------- */
  var box = document.getElementById('lightbox');
  if (!box) return;
  var boxImg = box.querySelector('.lightbox-img');
  var boxCap = box.querySelector('.lightbox-caption');
  var current = 0;

  function openLightbox(i) {
    current = i;
    show();
    box.hidden = false;
    document.body.style.overflow = 'hidden';
  }
  function closeLightbox() {
    box.hidden = true;
    document.body.style.overflow = '';
  }
  function show() {
    var img = images[current];
    if (!img) return;
    boxImg.src = img.file || img.thumb;
    boxImg.alt = img.name || '';
    boxCap.textContent = img.name || '';
  }
  function step(delta) {
    current = (current + delta + images.length) % images.length;
    show();
  }

  box.querySelector('.lightbox-close').addEventListener('click', closeLightbox);
  box.querySelector('.lightbox-next').addEventListener('click', function (e) { e.stopPropagation(); step(1); });
  box.querySelector('.lightbox-prev').addEventListener('click', function (e) { e.stopPropagation(); step(-1); });
  box.addEventListener('click', function (e) { if (e.target === box) closeLightbox(); });
  document.addEventListener('keydown', function (e) {
    if (box.hidden) return;
    if (e.key === 'Escape') closeLightbox();
    else if (e.key === 'ArrowRight') step(1);
    else if (e.key === 'ArrowLeft') step(-1);
  });
})();
